#!/bin/bash

build() {
    add_module "loop"
    add_module "dm-snapshot"
    add_module "overlay"
    add_module "zram"

    add_runscript

    add_binary blockdev
    add_binary mountpoint
    add_binary truncate
    add_binary rsync
    add_binary zramctl
    add_binary nproc
    add_binary free
    add_binary mkfs.ext4
    add_binary tune2fs

    add_file /usr/lib/udev/rules.d/10-dm.rules
    add_file /usr/lib/udev/rules.d/95-dm-notify.rules
    add_file /usr/lib/initcpio/udev/11-dm-initramfs.rules /usr/lib/udev/rules.d/11-dm-initramfs.rules
}
